name: Neon Database Backup to Google Drive

on:
  # Schedule to run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      retention_days:
        description: 'Number of days to check for data modifications'
        required: false
        default: '7'
        type: string
      cleanup_old_backups:
        description: 'Cleanup old backup files'
        required: false
        default: 'true'
        type: boolean
      cleanup_retention_days:
        description: 'Number of days to retain backups'
        required: false
        default: '30'
        type: string

env:
  NODE_VERSION: '20'

jobs:
  backup:
    name: Backup Neon Databases
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client-15

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Verify pg_dump installation
        run: |
          pg_dump --version
          which pg_dump

      - name: Run backup process
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          BACKUP_RETENTION_DAYS: ${{ github.event.inputs.retention_days || '7' }}
          CLEANUP_OLD_BACKUPS: ${{ github.event.inputs.cleanup_old_backups || 'true' }}
          CLEANUP_RETENTION_DAYS: ${{ github.event.inputs.cleanup_retention_days || '30' }}
          OUTPUT_DIR: './backups'
        run: node dist/index.js

      - name: Upload backup artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: backup-logs-${{ github.run_id }}
          path: |
            ./backups/*.log
            ./backups/*.sql
            ./backups/*.dump
          retention-days: 7

      - name: Cleanup local backups
        if: always()
        run: |
          rm -rf ./backups/*.sql ./backups/*.dump
          echo "Local backup files cleaned up"

  notify:
    name: Send notification
    needs: backup
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Send success notification
        if: needs.backup.result == 'success'
        run: |
          echo "✅ Neon database backup completed successfully"
          echo "Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"

      - name: Send failure notification
        if: needs.backup.result == 'failure'
        run: |
          echo "❌ Neon database backup failed"
          echo "Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo "Check the workflow logs for details"

      # Optional: Add Slack/Discord/Email notifications here
      # - name: Slack notification
      #   if: always()
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ needs.backup.result }}
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     text: |
      #       Neon Database Backup Status: ${{ needs.backup.result }}
      #       Repository: ${{ github.repository }}
      #       Workflow: ${{ github.workflow }}
      #       Run ID: ${{ github.run_id }}